In [1]:
# make the necessary imports
import numpy as np
from matplotlib import pyplot as plt
from Models.CustomClassifier import DecisionTree
from Utilities.Evaluate import evaluate


    

In [2]:
clean_dataset, noisy_dataset = np.loadtxt("Data/wifi_db/clean_dataset.txt", dtype = np.int32), np.loadtxt("Data/wifi_db/noisy_dataset.txt", dtype = np.float64)


In [3]:
print(" Shape of Clean Dataset : ", clean_dataset.shape)
print(" Shape of Noisy Dataset : ", noisy_dataset.shape)


 Shape of Clean Dataset :  (2000, 8)
 Shape of Noisy Dataset :  (2000, 8)


In [6]:

decision_tree = DecisionTree()

In [7]:
# K-Fold Cross-Validation
n_splits = 10
np.random.shuffle(clean_dataset)
n_samples = len(clean_dataset)
fold_size = n_samples // n_splits
indices = np.arange(n_samples)

    # Variables to accumulate results
total_cm = np.zeros((4, 4), dtype=int)  # Adjust for number of classes if needed
total_accuracy = 0
total_precision = np.zeros(4)  # Adjust for number of classes
total_recall = np.zeros(4)     # Adjust for number of classes
total_f1 = np.zeros(4)         # Adjust for number of classes

for i in range(n_splits):
    test_indices = indices[i * fold_size: (i + 1) * fold_size]
    train_indices = np.concatenate([indices[:i * fold_size], indices[(i + 1) * fold_size:]], axis = 0)

        # Prepare training and testing data
    train_set = clean_dataset[train_indices]
    test_set = clean_dataset[test_indices]

        # Train the decision tree
    decision_tree.fit(train_set)
       # Evaluate performance on the test fold
    cm, precision, recall, accuracy, f1 = evaluate(test_set, decision_tree, 4)
        
        #print(cm)
        
        
        
        # Accumulate results
    total_cm += cm
    total_accuracy += accuracy
    total_precision += precision
    total_recall += recall
    total_f1 += f1

    # Compute averages
    
average_cm = total_cm // n_splits
average_accuracy = total_accuracy / n_splits
average_precision = total_precision / n_splits
average_recall = total_recall / n_splits
average_f1 = total_f1 / n_splits

    # Print the results
print("Average Confusion Matrix:\n", average_cm)
print("Average Accuracy:", average_accuracy)
print("Average Precision per Class:", average_precision)
print("Average Recall per Class:", average_recall)
print("Average F1 Score per Class:", average_f1)


Average Confusion Matrix:
 [[49  0  0  0]
 [ 0 47  2  0]
 [ 0  1 47  0]
 [ 0  0  0 49]]
Average Accuracy: 0.9694999999999998
Average Precision per Class: [0.9864439  0.96199557 0.94613786 0.98312653]
Average Recall per Class: [0.98482256 0.95397633 0.9533359  0.98564694]
Average F1 Score per Class: [0.98554796 0.95748653 0.94903621 0.98433554]
